name: ChallengePlugin
main: at.mario.challenge.Main
version: 0.1.0
api-version: 1.21

depend: [CommandAPI]
softdepend: ['Multiverse-Core']

libraries:
  - "de.miraculixx:kpaper:1.1.2"
  - "dev.jorel:commandapi-bukkit-kotlin:9.5.2"